# template/.pre-commit-config.yaml
repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.29
  hooks:
    - id: uv-lock

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
    -   id: commitizen-branch
        stages: [pre-push]
        # This only checks if commits follow the conventional commits format
        # without doing any version bumping

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
        exclude: '.*\.csv$'
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.5
    hooks:
    -   id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
        # Run the linter
    -   id: ruff-format
        types_or: [ python, pyi ]
        # Run the formatter

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        exclude: ^tests/
        args: ["--config-file=pyproject.toml"]
        require_serial: true
        additional_dependencies: [
          "types-seaborn",
          "pandas-stubs",
        ]
