name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install commitizen

      - name: Get commit message
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Validate commit message format
        run: |
          if echo "${{ env.COMMIT_MSG }}" | grep -qE "^[a-z]+(\([^)]+\))?: "; then
            echo "Commit message follows conventional commit format."
          else
            echo "Commit message does not follow conventional commit format."
            exit 1
          fi

      - name: Attempt version bump (if applicable)
        run: |
          set -e
          COMMIT_MSG="${{ env.COMMIT_MSG }}"
          PACKAGE=""
          if echo "$COMMIT_MSG" | grep -qE "^[a-z]+\([^)]+\)"; then
            PACKAGE=$(echo "$COMMIT_MSG" | sed -n 's/^[a-z]\+(\([^)]\+\)).*/\1/p')
            if [ -d "packages/$PACKAGE" ]; then
              echo "Bumping version for package: $PACKAGE"
              cd "packages/$PACKAGE"
            else
              echo "Package '$PACKAGE' not found. Using root package."
            fi
          else
            echo "No package scope found. Using root package."
          fi

          # Run version bump.
          # If no bump is needed or if commitizen doesn’t modify files, that’s fine.
          cz bump --yes || echo "No version bump occurred."

          # If any changes were made, they’ll be staged/committed by commitizen.
          # Otherwise, we simply continue.

      - name: Push changes if commit message is valid
        run: git push --follow-tags
